Add files via upload
WingSyncAlgorithm/Flight_Optimization pull request #5
Opened 2023-12-20 06:40 UTC by codingcat12345

這是最原始版的rrt star之後可能還會再花幾周優化程式(改善進度會議報告提到的問題)

2023-12-20 19:49 UTC, jacky09299 requested changes
請符合程式撰寫規範

2023-12-20 19:49 UTC, jacky09299 commented on rrtstar.py
> +        p_rand=np.array([x_rand,y_rand])
```suggestion
        p_rand=np.array([x_rand,y_rand])
p是甚麼?這個縮寫不是常用的縮寫，會讓人沒辦法馬上看懂。你再檢查一下其他縮寫是不是也有問題，一併修改掉。縮寫不要縮得太多，要長到足夠讓人看懂。
```

2023-12-20 19:49 UTC, jacky09299 commented on rrtstar.py
> +class Block(pygame.sprite.Sprite):
```suggestion
class Block(pygame.sprite.Sprite):

```
class和def都應添加註釋，請參考程式撰寫規範

2023-12-20 19:51 UTC, jacky09299 commented
標題:Add files via upload
分支名稱:codingcat12345-patch-1

下次請用有意義的命名

2023-12-21 02:42 UTC, codingcat12345 commented on rrtstar.py
> +class Block(pygame.sprite.Sprite):
可以傳新版的程式撰寫規範給我嗎?我只有舊版的，不知道class和def怎麼註解 P是random產生的東西，至於她是甚麼意義不大，所以就隨便給個代號不過在這邊是指point

2023-12-21 04:35 UTC, jacky09299 commented
要完整寫point，不然別人不知道是甚麼東西在random。使用縮寫時必須讓人看懂。

codingcat12345 ***@***.***> 於 2023年12月21日 週四 上午10:42寫道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In rrtstar.py
> <https://github.com/WingSyncAlgorithm/Flight_Optimization/pull/5#discussion_r1433388326>
> :
>
> > @@ -0,0 +1,128 @@
> +import sys, pygame
> +import random
> +import numpy as np
> +
> +class Block(pygame.sprite.Sprite):
>
> 可以傳新版的程式撰寫規範給我嗎?我只有舊版的，不知道class和def怎麼註解
> P是random產生的東西，至於她是甚麼意義不大，所以就隨便給個代號不過在這邊是指point
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WingSyncAlgorithm/Flight_Optimization/pull/5#discussion_r1433388326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APYMQRFOAFEED7P42UEZZ2DYKOOY3AVCNFSM6AAAAABA4J72JWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJSGA2TEMBTGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2023-12-21 04:42 UTC, jacky09299 commented
像是rand大家知道是random的意思，可以縮寫。但p可以是point, probability, ...，人家看的時候要找到 p_rand=np.
array([x_rand,y_rand])這行程式碼，才知道這是甚麼。

李紘宇 ***@***.***> 於 2023年12月21日 週四 下午12:35寫道：

> 要完整寫point，不然別人不知道是甚麼東西在random。使用縮寫時必須讓人看懂。
>
> codingcat12345 ***@***.***> 於 2023年12月21日 週四 上午10:42寫道：
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In rrtstar.py
>> <https://github.com/WingSyncAlgorithm/Flight_Optimization/pull/5#discussion_r1433388326>
>> :
>>
>> > @@ -0,0 +1,128 @@
>> +import sys, pygame
>> +import random
>> +import numpy as np
>> +
>> +class Block(pygame.sprite.Sprite):
>>
>> 可以傳新版的程式撰寫規範給我嗎?我只有舊版的，不知道class和def怎麼註解
>> P是random產生的東西，至於她是甚麼意義不大，所以就隨便給個代號不過在這邊是指point
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/WingSyncAlgorithm/Flight_Optimization/pull/5#discussion_r1433388326>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/APYMQRFOAFEED7P42UEZZ2DYKOOY3AVCNFSM6AAAAABA4J72JWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJSGA2TEMBTGA>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***
>> com>
>>
>

2023-12-21 09:08 UTC, codingcat12345 commented
要怎麼提交改好的程式?

2023-12-21 10:33 UTC, jacky09299 commented
> 要怎麼提交改好的程式?

把修改完的程式push到你的分支之後，點進你原本的pull request，按下右邊的Re-request review
![unnamed](https://github.com/WingSyncAlgorithm/Flight_Optimization/assets/66111556/8636cbcd-9c8f-487e-b76d-5294aa8dd7fd)

2023-12-22 04:30 UTC, codingcat12345 commented
ok，感謝

2023-12-22 04:52 UTC, jacky09299 approved these changes
Good

2023-12-22 04:52 UTC, merged